/* Generated By:JavaCC: Do not edit this line. SymbolicParserConstants.java */
package softtest.domain.c.symbolic.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SymbolicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 4;
  /** RegularExpression Id. */
  int NUM = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "<ID>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
