/* Generated By:JavaCC: Do not edit this line. CParser_GCCTreeConstants.java Version 5.0 */
package softtest.ast.gccparser.c;

public interface CParser_GCCTreeConstants
{
  public int JJTTRANSLATIONUNIT = 0;
  public int JJTEXTERNALDECLARATION = 1;
  public int JJTFUNCTIONDECLARATION = 2;
  public int JJTFUNCTIONDEFINITION = 3;
  public int JJTDECLARATION = 4;
  public int JJTDECLARATIONLIST = 5;
  public int JJTNESTEDFUNCTIONDECLARATION = 6;
  public int JJTNESTEDFUNCTIONDEFINITION = 7;
  public int JJTLABELDECLARATIONLIST = 8;
  public int JJTLABELDECLARATION = 9;
  public int JJTLABELDECLARATORLIST = 10;
  public int JJTLABELDECLARATOR = 11;
  public int JJTLABELTYPE = 12;
  public int JJTDECLARATIONSPECIFIERS = 13;
  public int JJTTYPEOFDECLARATIONSPECIFIER = 14;
  public int JJTSTORAGECLASSSPECIFIER = 15;
  public int JJTTYPESPECIFIER = 16;
  public int JJTTYPEQUALIFIER = 17;
  public int JJTSTRUCTORUNIONSPECIFIER = 18;
  public int JJTSTRUCTORUNION = 19;
  public int JJTSTRUCTDECLARATIONLIST = 20;
  public int JJTINITDECLARATORLIST = 21;
  public int JJTINITDECLARATOR = 22;
  public int JJTSTRUCTDECLARATION = 23;
  public int JJTSPECIFIERQUALIFIERLIST = 24;
  public int JJTSTRUCTDECLARATORLIST = 25;
  public int JJTSTRUCTDECLARATOR = 26;
  public int JJTENUMSPECIFIER = 27;
  public int JJTENUMERATORLIST = 28;
  public int JJTENUMERATOR = 29;
  public int JJTDECLARATOR = 30;
  public int JJTDIRECTDECLARATOR = 31;
  public int JJTPOINTER = 32;
  public int JJTTYPEQUALIFIERLIST = 33;
  public int JJTPARAMETERTYPELIST = 34;
  public int JJTPARAMETERLIST = 35;
  public int JJTPARAMETERDECLARATION = 36;
  public int JJTIDENTIFIERLIST = 37;
  public int JJTINITIALIZER = 38;
  public int JJTINITIALIZERLIST = 39;
  public int JJTTYPENAME = 40;
  public int JJTABSTRACTDECLARATOR = 41;
  public int JJTDIRECTABSTRACTDECLARATOR = 42;
  public int JJTTYPEDEFNAME = 43;
  public int JJTSTATEMENT = 44;
  public int JJTLABELEDSTATEMENT = 45;
  public int JJTEXPRESSIONSTATEMENT = 46;
  public int JJTCOMPOUNDSTATEMENT = 47;
  public int JJTSTATEMENTLIST = 48;
  public int JJTSELECTIONSTATEMENT = 49;
  public int JJTITERATIONSTATEMENT = 50;
  public int JJTJUMPSTATEMENT = 51;
  public int JJTEXPRESSION = 52;
  public int JJTASSIGNMENTEXPRESSION = 53;
  public int JJTASSIGNMENTOPERATOR = 54;
  public int JJTCONDITIONALEXPRESSION = 55;
  public int JJTCONSTANTEXPRESSION = 56;
  public int JJTLOGICALOREXPRESSION = 57;
  public int JJTLOGICALANDEXPRESSION = 58;
  public int JJTINCLUSIVEOREXPRESSION = 59;
  public int JJTEXCLUSIVEOREXPRESSION = 60;
  public int JJTANDEXPRESSION = 61;
  public int JJTEQUALITYEXPRESSION = 62;
  public int JJTRELATIONALEXPRESSION = 63;
  public int JJTSHIFTEXPRESSION = 64;
  public int JJTADDITIVEEXPRESSION = 65;
  public int JJTMULTIPLICATIVEEXPRESSION = 66;
  public int JJTCASTEXPRESSION = 67;
  public int JJTUNARYEXPRESSION = 68;
  public int JJTUNARYOPERATOR = 69;
  public int JJTFIELDID = 70;
  public int JJTPOSTFIXEXPRESSION = 71;
  public int JJTPRIMARYEXPRESSION = 72;
  public int JJTARGUMENTEXPRESSIONLIST = 73;
  public int JJTCONSTANT = 74;


  public String[] jjtNodeName = {
    "TranslationUnit",
    "ExternalDeclaration",
    "FunctionDeclaration",
    "FunctionDefinition",
    "Declaration",
    "DeclarationList",
    "NestedFunctionDeclaration",
    "NestedFunctionDefinition",
    "LabelDeclarationList",
    "LabelDeclaration",
    "LabelDeclaratorList",
    "LabelDeclarator",
    "LabelType",
    "DeclarationSpecifiers",
    "TypeofDeclarationSpecifier",
    "StorageClassSpecifier",
    "TypeSpecifier",
    "TypeQualifier",
    "StructOrUnionSpecifier",
    "StructOrUnion",
    "StructDeclarationList",
    "InitDeclaratorList",
    "InitDeclarator",
    "StructDeclaration",
    "SpecifierQualifierList",
    "StructDeclaratorList",
    "StructDeclarator",
    "EnumSpecifier",
    "EnumeratorList",
    "Enumerator",
    "Declarator",
    "DirectDeclarator",
    "Pointer",
    "TypeQualifierList",
    "ParameterTypeList",
    "ParameterList",
    "ParameterDeclaration",
    "IdentifierList",
    "Initializer",
    "InitializerList",
    "TypeName",
    "AbstractDeclarator",
    "DirectAbstractDeclarator",
    "TypedefName",
    "Statement",
    "LabeledStatement",
    "ExpressionStatement",
    "CompoundStatement",
    "StatementList",
    "SelectionStatement",
    "IterationStatement",
    "JumpStatement",
    "Expression",
    "AssignmentExpression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConstantExpression",
    "LogicalORExpression",
    "LogicalANDExpression",
    "InclusiveORExpression",
    "ExclusiveORExpression",
    "ANDExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "CastExpression",
    "UnaryExpression",
    "UnaryOperator",
    "FieldId",
    "PostfixExpression",
    "PrimaryExpression",
    "ArgumentExpressionList",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=db610033bb4d7f372f5a6d10eed79eb4 (do not edit this line) */
