/* Generated By:JJTree: Do not edit this line. ASTAssignmentExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTAssignmentExpression extends AbstractExpression {
  public ASTAssignmentExpression(int id) {
    super(id);
  }

  public ASTAssignmentExpression(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=405d3a03f519a10cfd92bee2bd4c9460 (do not edit this line) */
