/* Generated By:JJTree: Do not edit this line. ASTAbstractDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import softtest.symboltable.c.Type.CType;

public class ASTAbstractDeclarator extends SimpleNode {
	CType type = null;

	public ASTAbstractDeclarator(int id) {
		super(id);
	}

	public ASTAbstractDeclarator(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}
}
/* JavaCC - OriginalChecksum=ba22a88388844db6a46fe3576db492f0 (do not edit this line) */
