/* Generated By:JJTree: Do not edit this line. ASTConstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTConstant extends AbstractExpression {
  public ASTConstant(int id) {
    super(id);
  }

  public ASTConstant(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  //zys:2010.4.15	表示每个常量的整型数值
  private long value;

public long getValue() {
	return value;
}

public void setValue(long value2) {
	this.value = value2;
} 
}
/* JavaCC - OriginalChecksum=f795952f236766dc189cb9a9e2819df7 (do not edit this line) */
