/* Generated By:JJTree: Do not edit this line. ASTDirectAbstractDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import java.util.ArrayList;

import softtest.symboltable.c.Type.CType;

public class ASTDirectAbstractDeclarator extends SimpleNode {
	CType type = null;
	
	ArrayList<Boolean> flags = new ArrayList<Boolean>();

	public ASTDirectAbstractDeclarator(int id) {
		super(id);
	}

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}

	public ASTDirectAbstractDeclarator(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public ArrayList<Boolean> getFlags() {
		return flags;
	}

	public void setFlags(ArrayList<Boolean> flags) {
		this.flags = flags;
	}
	
	void setFlag(boolean flag){
		flags.add(flag);
	}
	
	public void setOperatorTypeAndFlag(String str,boolean flag){
		this.setOperatorType(str);
		this.setFlag(flag);
	}
}
/* JavaCC - OriginalChecksum=ab01f080bb190868efce846f63fb7dc8 (do not edit this line) */
