/* Generated By:JJTree: Do not edit this line. ASTDeclarationSpecifiers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import java.util.*;

import softtest.symboltable.c.Type.CType;

public class ASTDeclarationSpecifiers extends SimpleNode {
	CType type = null;
	
	boolean typehandled = false;

	public boolean isTypehandled() {
		return typehandled;
	}

	public void setTypehandled(boolean typehandled) {
		this.typehandled = typehandled;
	}

	public ASTDeclarationSpecifiers(int id) {
		super(id);
	}

	public ASTDeclarationSpecifiers(CParser p, int id) {
		super(p, id);
	}
	
	public List<ASTDeclarationSpecifiers> findAllNestDeclarationSpecifiers(){
		List<ASTDeclarationSpecifiers> list =new ArrayList<ASTDeclarationSpecifiers>();
		ASTDeclarationSpecifiers node=this;
		list.add(this);
		while(node.jjtGetNumChildren()==2&&node.jjtGetChild(1) instanceof ASTDeclarationSpecifiers){
			node = (ASTDeclarationSpecifiers)node.jjtGetChild(1);
			list.add(node);
		}
		return list;
	}
	
	public List<ASTStorageClassSpecifier> findAllNestStorageClassSpecifier(){
		List<ASTStorageClassSpecifier> list =new ArrayList<ASTStorageClassSpecifier>();
		ASTDeclarationSpecifiers node=this;
		if(node.jjtGetChild(0) instanceof ASTStorageClassSpecifier){
			list.add((ASTStorageClassSpecifier)node.jjtGetChild(0));
		}
		while(node.jjtGetNumChildren()==2&&node.jjtGetChild(1) instanceof ASTDeclarationSpecifiers){
			node = (ASTDeclarationSpecifiers)node.jjtGetChild(1);
			if(node.jjtGetChild(0) instanceof ASTStorageClassSpecifier){
				list.add((ASTStorageClassSpecifier)node.jjtGetChild(0));
			}
		}
		return list;	
	}
	
	
	public List<ASTTypeSpecifier> findAllNestTypeSpecifier(){
		List<ASTTypeSpecifier> list =new ArrayList<ASTTypeSpecifier>();
		ASTDeclarationSpecifiers node=this;
		if(node.jjtGetChild(0) instanceof ASTTypeSpecifier){
			list.add((ASTTypeSpecifier)node.jjtGetChild(0));
		}
		while(node.jjtGetNumChildren()==2&&node.jjtGetChild(1) instanceof ASTDeclarationSpecifiers){
			node = (ASTDeclarationSpecifiers)node.jjtGetChild(1);
			if(node.jjtGetChild(0) instanceof ASTTypeSpecifier){
				list.add((ASTTypeSpecifier)node.jjtGetChild(0));
			}
		}
		return list;	
	}
	
	
	public List<ASTTypeQualifier> findAllNestTypeQualifier(){
		List<ASTTypeQualifier> list =new ArrayList<ASTTypeQualifier>();
		ASTDeclarationSpecifiers node=this;
		if(node.jjtGetChild(0) instanceof ASTTypeQualifier){
			list.add((ASTTypeQualifier)node.jjtGetChild(0));
		}
		while(node.jjtGetNumChildren()==2&&node.jjtGetChild(1) instanceof ASTDeclarationSpecifiers){
			node = (ASTDeclarationSpecifiers)node.jjtGetChild(1);
			if(node.jjtGetChild(0) instanceof ASTTypeQualifier){
				list.add((ASTTypeQualifier)node.jjtGetChild(0));
			}
		}
		return list;	
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}
}
/* JavaCC - OriginalChecksum=8f4183f943ee4e79e729588459207091 (do not edit this line) */
