/* Generated By:JJTree: Do not edit this line. ASTExclusiveORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTExclusiveORExpression extends AbstractExpression {
  public ASTExclusiveORExpression(int id) {
    super(id);
  }

  public ASTExclusiveORExpression(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cf9284e297f451cc92b9a2bd748fcd93 (do not edit this line) */
