/* Generated By:JJTree: Do not edit this line. ASTEnumSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import softtest.symboltable.c.ClassNameDeclaration;
import softtest.symboltable.c.Type.CType;

public class ASTEnumSpecifier extends SimpleNode {
	CType type = null;
	
	ClassNameDeclaration decl;

	public ClassNameDeclaration getDecl() {
		return decl;
	}

	public void setDecl(ClassNameDeclaration decl) {
		this.decl = decl;
	}

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}

	public ASTEnumSpecifier(int id) {
		super(id);
	}

	public ASTEnumSpecifier(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=b10df6d8a3fc8de9501eb29792ad6003 (do not edit this line) */
