/* Generated By:JJTree: Do not edit this line. ASTExternalDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTExternalDeclaration extends SimpleNode {
  public ASTExternalDeclaration(int id) {
    super(id);
  }

  public ASTExternalDeclaration(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=87fe483b6f60d44b3ade1300688a649e (do not edit this line) */
