/* Generated By:JJTree: Do not edit this line. ASTFieldId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import softtest.symboltable.c.VariableNameDeclaration;

public class ASTFieldId extends AbstractExpression {

	private VariableNameDeclaration v;

	public ASTFieldId(int id) {
		super(id);
	}

	public ASTFieldId(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setVariableNameDeclaration(VariableNameDeclaration v) {
		this.v = v;
	}

	public VariableNameDeclaration getVariableNameDeclaration() {
		return v;
	}
}
/* JavaCC - OriginalChecksum=3c2e999c582b053763ea2760197ed2ca (do not edit this line) */
