/* Generated By:JJTree: Do not edit this line. ASTInclusiveORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTInclusiveORExpression extends AbstractExpression {
  public ASTInclusiveORExpression(int id) {
    super(id);
  }

  public ASTInclusiveORExpression(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=86fac8f3deafdd721ebb843bdf91ed7d (do not edit this line) */
