/* Generated By:JJTree: Do not edit this line. ASTIdentifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import java.util.ArrayList;

import softtest.symboltable.c.Type.CType;

public class ASTIdentifierList extends SimpleNode {
	ArrayList<String> identifiers = new ArrayList<String>();
	
	CType type = null;

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}

	public ASTIdentifierList(int id) {
		super(id);
	}

	public ASTIdentifierList(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public ArrayList<String> getIdentifiers() {
		return identifiers;
	}

	public void setIdentifiers(ArrayList<String> identifiers) {
		this.identifiers = identifiers;
	}
	
	public void addIndentifier(String identifier){
		identifiers.add(identifier);
	}
}
/* JavaCC - OriginalChecksum=2f2df2a69f9b238324c862dfbb12eadf (do not edit this line) */
