/* Generated By:JJTree: Do not edit this line. ASTInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import java.util.*;

public
class ASTInitializer extends SimpleNode {
  public ASTInitializer(int id) {
    super(id);
  }

  public ASTInitializer(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public List<Integer> getDimSize(){
	  List<Integer> list=new ArrayList<Integer>();
	  ASTInitializerList initlist =(ASTInitializerList)this.getSingleChildofType(ASTInitializerList.class);
	  if(initlist!=null){
		  list=initlist.getDimSize();
		  list.add(0, initlist.jjtGetNumChildren());
	  }
	  return list;
  }
}
/* JavaCC - OriginalChecksum=535421b24a02eeb68a41de0687ad3f98 (do not edit this line) */
