/* Generated By:JJTree: Do not edit this line. ASTInitializerList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import java.util.ArrayList;
import java.util.List;

public
class ASTInitializerList extends SimpleNode {
  public ASTInitializerList(int id) {
    super(id);
  }

  public ASTInitializerList(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public List<Integer> getDimSize(){
	  ArrayList<Integer> list=new ArrayList<Integer>();
	  for(int i=0;i<jjtGetNumChildren();i++){
		  ASTInitializer init=(ASTInitializer)this.jjtGetChild(i);
		  List<Integer> temp=init.getDimSize();
		  for(int j=0;j<temp.size();j++){
			  int size=temp.get(j);
			  if(j>=list.size()){
				  list.add(size);
			  }else{
				  if(size>list.get(j)){
					  list.set(j, size);
				  }
			  }
		  }
	  }
	  return list;
  }
}
/* JavaCC - OriginalChecksum=b98f96f591ef6316670e9b9161975b01 (do not edit this line) */
