/* Generated By:JJTree: Do not edit this line. ASTInterrupt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public class ASTInterrupt extends SimpleNode {
	String internum = "";

	public ASTInterrupt(int id) {
		super(id);
	}

	public ASTInterrupt(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String getInternum() {
		return internum;
	}

	public void setInternum(String internum) {
		this.internum = internum;
	}
}
/* JavaCC - OriginalChecksum=8dc6b79054d1a64ce5c562dc1ffa963d (do not edit this line) */
