/* Generated By:JJTree: Do not edit this line. ASTLabelDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTLabelDeclarationList extends SimpleNode {
  public ASTLabelDeclarationList(int id) {
    super(id);
  }

  public ASTLabelDeclarationList(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=74b96a85f0f29d7073ff7399500a1086 (do not edit this line) */
