/* Generated By:JJTree: Do not edit this line. ASTLogicalORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTLogicalORExpression extends AbstractExpression {
  public ASTLogicalORExpression(int id) {
    super(id);
  }

  public ASTLogicalORExpression(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=345a8dfd3f8e97cbfacbde0600e19ef3 (do not edit this line) */
