/* Generated By:JJTree: Do not edit this line. ASTLogicalANDExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTLogicalANDExpression extends AbstractExpression {
  public ASTLogicalANDExpression(int id) {
    super(id);
  }

  public ASTLogicalANDExpression(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bfa905a09e2707a32f10ffae0dd0e457 (do not edit this line) */
