/* Generated By:JJTree: Do not edit this line. ASTLabelDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTLabelDeclaration extends SimpleNode {
  public ASTLabelDeclaration(int id) {
    super(id);
  }

  public ASTLabelDeclaration(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=74763d57753f88e53a3fd41fd0af7424 (do not edit this line) */
