/* Generated By:JJTree: Do not edit this line. ASTMemoryModel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTMemoryModel extends SimpleNode {
  public ASTMemoryModel(int id) {
    super(id);
  }

  public ASTMemoryModel(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75051c58b3d125ec45b9ee0a694ea4b6 (do not edit this line) */
