/* Generated By:JJTree: Do not edit this line. ASTNestedFunctionDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import softtest.cfg.c.Graph;
import softtest.symboltable.c.MethodNameDeclaration;
import softtest.symboltable.c.Type.CType;

public class ASTNestedFunctionDefinition extends SimpleNode {
	Graph graph;
	
	CType type = null;
	
	MethodNameDeclaration decl;
	
	public MethodNameDeclaration getDecl() {
		return decl;
	}

	public void setDecl(MethodNameDeclaration decl) {
		this.decl = decl;
	}

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}

	@Override
	public String getImage() {
		if(image.equals("")){
			SimpleNode child=(SimpleNode)this.getFirstDirectChildOfType(ASTDeclarator.class);
			if(child!=null){
				image=child.getImage();
			}
		}
		return image;
	}

	public ASTNestedFunctionDefinition(int id) {
		super(id);
	}

	public ASTNestedFunctionDefinition(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public Graph getGraph() {
		return graph;
	}

	public void setGraph(Graph graph) {
		this.graph = graph;
	}
}
/*
 * JavaCC - OriginalChecksum=98e2bc20f7894a84aa9db1d2e376aae7 (do not edit this
 * line)
 */
