/* Generated By:JJTree: Do not edit this line. ASTParameterTypeList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import softtest.symboltable.c.Type.CType;

public class ASTParameterTypeList extends SimpleNode {
	CType type = null;
	boolean vararg = false;

	public ASTParameterTypeList(int id) {
		super(id);
	}

	public ASTParameterTypeList(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public boolean isVararg() {
		return vararg;
	}

	public void setVararg(boolean vararg) {
		this.vararg = vararg;
	}

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}
}
/* JavaCC - OriginalChecksum=10e78dd10a49a8d5de0dcf6485dd1630 (do not edit this line) */
