/* Generated By:JJTree: Do not edit this line. ASTStructOrUnion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTStructOrUnion extends SimpleNode {
  public ASTStructOrUnion(int id) {
    super(id);
  }

  public ASTStructOrUnion(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db46f794447978a179b4d82e727d2077 (do not edit this line) */
