/* Generated By:JJTree: Do not edit this line. ASTStructDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTStructDeclarationList extends SimpleNode {
  public ASTStructDeclarationList(int id) {
    super(id);
  }

  public ASTStructDeclarationList(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=244bb0b7d172599e0d485b6bac41e716 (do not edit this line) */
