/* Generated By:JJTree: Do not edit this line. ASTStructDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

import softtest.symboltable.c.Type.CType;

public class ASTStructDeclarator extends SimpleNode {
	CType type = null;

	public ASTStructDeclarator(int id) {
		super(id);
	}

	public ASTStructDeclarator(CParser p, int id) {
		super(p, id);
	}

	public CType getType() {
		return type;
	}

	public void setType(CType type) {
		this.type = type;
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=afbcd9e17d990702eb40f25164338954 (do not edit this
 * line)
 */
