/* Generated By:JJTree: Do not edit this line. ASTStorageClassSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public class ASTStorageClassSpecifier extends SimpleNode {
	boolean typehandled = false;

	public boolean isTypehandled() {
		return typehandled;
	}

	public void setTypehandled(boolean typehandled) {
		this.typehandled = typehandled;
	}

	public ASTStorageClassSpecifier(int id) {
		super(id);
	}

	public ASTStorageClassSpecifier(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=4693b80e5067365c3ad5c397448e5ba5 (do not edit this line) */
