/* Generated By:JJTree: Do not edit this line. ASTTypeQualifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public class ASTTypeQualifier extends SimpleNode {
	boolean typehandled = false;

	public boolean isTypehandled() {
		return typehandled;
	}

	public void setTypehandled(boolean typehandled) {
		this.typehandled = typehandled;
	}

	public ASTTypeQualifier(int id) {
		super(id);
	}

	public ASTTypeQualifier(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=140478d7cf39b469e22cb122d372241a (do not edit this line) */
