/* Generated By:JJTree: Do not edit this line. ASTTypeQualifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public
class ASTTypeQualifierList extends SimpleNode {
  public ASTTypeQualifierList(int id) {
    super(id);
  }

  public ASTTypeQualifierList(CParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ecfea91bc1d4adf8abe9db31c712bdbf (do not edit this line) */
