/* Generated By:JJTree: Do not edit this line. ASTUsing.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package softtest.ast.c;

public class ASTUsing extends SimpleNode {
	String usingnum = "";

	public ASTUsing(int id) {
		super(id);
	}

	public ASTUsing(CParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String getUsingnum() {
		return usingnum;
	}

	public void setUsingnum(String usingnum) {
		this.usingnum = usingnum;
	}
}
/* JavaCC - OriginalChecksum=ca9892d9212bb54904730064c636a813 (do not edit this line) */
