/* Generated By:JavaCC: Do not edit this line. CParser_KeilTreeConstants.java Version 5.0 */
package softtest.ast.keilparser.c;

public interface CParser_KeilTreeConstants
{
  public int JJTTRANSLATIONUNIT = 0;
  public int JJTEXTERNALDECLARATION = 1;
  public int JJTPRAGMA = 2;
  public int JJTINTERRUPT = 3;
  public int JJTUSING = 4;
  public int JJTREENTRANT = 5;
  public int JJTPRIORITY = 6;
  public int JJTTASK = 7;
  public int JJTMEMORYMODEL = 8;
  public int JJTFUNCTIONDEFINITION = 9;
  public int JJTFUNCTIONDECLARATION = 10;
  public int JJTDECLARATION = 11;
  public int JJTDECLARATIONLIST = 12;
  public int JJTDECLARATIONSPECIFIERS = 13;
  public int JJTSTORAGECLASSSPECIFIER = 14;
  public int JJTTYPESPECIFIER = 15;
  public int JJTTYPEQUALIFIER = 16;
  public int JJTSTRUCTORUNIONSPECIFIER = 17;
  public int JJTSTRUCTORUNION = 18;
  public int JJTSTRUCTDECLARATIONLIST = 19;
  public int JJTINITDECLARATORLIST = 20;
  public int JJTINITDECLARATOR = 21;
  public int JJTSTRUCTDECLARATION = 22;
  public int JJTSPECIFIERQUALIFIERLIST = 23;
  public int JJTSTRUCTDECLARATORLIST = 24;
  public int JJTSTRUCTDECLARATOR = 25;
  public int JJTENUMSPECIFIER = 26;
  public int JJTENUMERATORLIST = 27;
  public int JJTENUMERATOR = 28;
  public int JJTDECLARATOR = 29;
  public int JJTDIRECTDECLARATOR = 30;
  public int JJTPOINTER = 31;
  public int JJTTYPEQUALIFIERLIST = 32;
  public int JJTPARAMETERTYPELIST = 33;
  public int JJTPARAMETERLIST = 34;
  public int JJTPARAMETERDECLARATION = 35;
  public int JJTIDENTIFIERLIST = 36;
  public int JJTINITIALIZER = 37;
  public int JJTINITIALIZERLIST = 38;
  public int JJTTYPENAME = 39;
  public int JJTABSTRACTDECLARATOR = 40;
  public int JJTDIRECTABSTRACTDECLARATOR = 41;
  public int JJTTYPEDEFNAME = 42;
  public int JJTSTATEMENT = 43;
  public int JJTLABELEDSTATEMENT = 44;
  public int JJTEXPRESSIONSTATEMENT = 45;
  public int JJTCOMPOUNDSTATEMENT = 46;
  public int JJTSTATEMENTLIST = 47;
  public int JJTSELECTIONSTATEMENT = 48;
  public int JJTITERATIONSTATEMENT = 49;
  public int JJTJUMPSTATEMENT = 50;
  public int JJTEXPRESSION = 51;
  public int JJTASSIGNMENTEXPRESSION = 52;
  public int JJTASSIGNMENTOPERATOR = 53;
  public int JJTCONDITIONALEXPRESSION = 54;
  public int JJTCONSTANTEXPRESSION = 55;
  public int JJTLOGICALOREXPRESSION = 56;
  public int JJTLOGICALANDEXPRESSION = 57;
  public int JJTINCLUSIVEOREXPRESSION = 58;
  public int JJTEXCLUSIVEOREXPRESSION = 59;
  public int JJTANDEXPRESSION = 60;
  public int JJTEQUALITYEXPRESSION = 61;
  public int JJTRELATIONALEXPRESSION = 62;
  public int JJTSHIFTEXPRESSION = 63;
  public int JJTADDITIVEEXPRESSION = 64;
  public int JJTMULTIPLICATIVEEXPRESSION = 65;
  public int JJTCASTEXPRESSION = 66;
  public int JJTUNARYEXPRESSION = 67;
  public int JJTUNARYOPERATOR = 68;
  public int JJTFIELDID = 69;
  public int JJTPOSTFIXEXPRESSION = 70;
  public int JJTPRIMARYEXPRESSION = 71;
  public int JJTARGUMENTEXPRESSIONLIST = 72;
  public int JJTCONSTANT = 73;


  public String[] jjtNodeName = {
    "TranslationUnit",
    "ExternalDeclaration",
    "PRAGMA",
    "Interrupt",
    "Using",
    "Reentrant",
    "Priority",
    "Task",
    "MemoryModel",
    "FunctionDefinition",
    "FunctionDeclaration",
    "Declaration",
    "DeclarationList",
    "DeclarationSpecifiers",
    "StorageClassSpecifier",
    "TypeSpecifier",
    "TypeQualifier",
    "StructOrUnionSpecifier",
    "StructOrUnion",
    "StructDeclarationList",
    "InitDeclaratorList",
    "InitDeclarator",
    "StructDeclaration",
    "SpecifierQualifierList",
    "StructDeclaratorList",
    "StructDeclarator",
    "EnumSpecifier",
    "EnumeratorList",
    "Enumerator",
    "Declarator",
    "DirectDeclarator",
    "Pointer",
    "TypeQualifierList",
    "ParameterTypeList",
    "ParameterList",
    "ParameterDeclaration",
    "IdentifierList",
    "Initializer",
    "InitializerList",
    "TypeName",
    "AbstractDeclarator",
    "DirectAbstractDeclarator",
    "TypedefName",
    "Statement",
    "LabeledStatement",
    "ExpressionStatement",
    "CompoundStatement",
    "StatementList",
    "SelectionStatement",
    "IterationStatement",
    "JumpStatement",
    "Expression",
    "AssignmentExpression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConstantExpression",
    "LogicalORExpression",
    "LogicalANDExpression",
    "InclusiveORExpression",
    "ExclusiveORExpression",
    "ANDExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "CastExpression",
    "UnaryExpression",
    "UnaryOperator",
    "FieldId",
    "PostfixExpression",
    "PrimaryExpression",
    "ArgumentExpressionList",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=fefd25e419a448b0737a5f8331a2e56c (do not edit this line) */
