package softtest.summary.c;

public enum MethodFeatureType {
	PRECOND_NPD,
	FEATURE_MM,
	PRECOND_BO,
	FEATURE_TDIN,
	FEATRUE_RM,
	FEATRUE_RR,
	RESERVED,
	FEATURE_TDUSE,
	FEATURE_TDPROPA,
	BO_PRECON,
	API_ABUSE,
	UNCK_RET_VALUE,
	REQUIRE_RESTRICTON,
	PWD_FILE_RELATED,
	BSTR,
	ALLOC,
	FREE,
}
